---
# tasks file for init_disable_ipv6

- name: "{{ mPlayMsg }}{{role_path|basename}} | Initiate local facts"
  set_fact:
    mMainMsg: "{{ mPlayMsg }}{{role_path|basename}} | "

- name: "{{ mMainMsg }}Set net.ipv6.conf.all.disable_ipv6"
  become: true
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: '1'
    state: present

- name: "{{ mMainMsg }}Set net.ipv6.conf.default.disable_ipv6"
  become: true
  ansible.posix.sysctl:
    name: net.ipv6.conf.default.disable_ipv6
    value: '1'
    state: present
