# ---

# Initialisation

- name: "Initialisation"
  hosts: tdp
  pre_tasks:
    - name: "{{ ansible_play_name }} | Initiate local facts"
      set_fact:
        mPlayMsg: "{{ ansible_play_name }} | "
  roles:
    - init_hostname
    - init_data_disks
    - init_disable_ipv6
